[package]
name = "meta"
version = "0.1.0"
authors = ["Josh Austin <josh.austin@gmail.com>"]

[lib]
name = "libmeta"
path = "src/lib.rs"

[[bin]]
name = "meta"
path = "src/main.rs"

[dependencies]
lmdb-rs = "0.7.6"
memmap = "0.6.1"
sysconf = "0.3.1"
rand = "0.3.17"
